# Configuração do SonarQube / SonarCloud para análise estática de código (SAST)

sonar.organization=MisaelSarda
sonar.projectKey=MisaelSarda_projeto-sdd-aws

sonar.projectName=Projeto SDD AWS API

# Definição dos diretórios de código e testes
sonar.sources=app
sonar.tests=tests

# Caminho do relatório de cobertura gerado pelo pytest-cov
sonar.python.coverage.reportPaths=coverage.xml

# Codificação
sonar.sourceEncoding=UTF-8

# Exclusões de arquivos de infraestrutura e documentação
sonar.exclusions=docs/**,docker-compose.yml,Dockerfile

# Faz a pipeline AGUARDAR o Quality Gate e FALHAR se ele reprovar
sonar.qualitygate.wait=true
